[project]
name = "betterlogging"
version = "0.1.0"
authors = [{name="Regan Willis", email="reganwillis@outlook.com"}]
description = "Better Logging"
dependencies = [
	"rich"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
